const Languages = {
    common: {
        cancel: 'Hủy',
        ok: 'Chọn',
        back: 'Quay lại',
        yes: 'Có',
        no: 'Không',
        close: 'Đóng',
        search: 'Tìm kiếm',
        agree: 'Đồng ý',
        or: 'Hoặc',
        continue: 'Tiếp tục',
        currency: 'VND',
        percent: '%',
        mustChoose: '*',
        input: 'Nhập',
        add: 'Thêm',
        filter: 'Bộ lọc',
        filterCancel: 'Bỏ lọc',
        save: 'Lưu',
        notFound: 'Không tìm thấy dữ liệu',
        update: 'Cập nhật'
    },
    errorMsg: {
        noInternet: 'Kết nối bị gián đoạn, vui lòng thử lại!',
        sessionExpired: 'Kết nối bị gián đoạn, vui lòng thử lại!',
        positionRequired: 'Thông tin phân quyền chức vụ không được để trống',
        userNameRequired: 'Họ và tên không được để trống',
        userInfoLength: 'Thông tin không được để trống',
        imageRequired: 'Hình ảnh không được để trống',
        userInfoRegex: 'Không được chứa ký tự đặc biệt hoặc chữ',
        userNameLength: 'Họ và tên không được ít hơn 8 ký tự',
        userNameEmpty: 'Họ tên không được để trống',
        userNameRegex: 'Trường họ tên không được chứa ký tự đặc biệt hoặc số',
        errIllegal: 'Mật khẩu không hợp lệ',
        nameRequired: 'Tên không được để trống',
        emailNull: 'Email không được để trống',
        emailRegex: 'Email không đúng định dạng',
        cardNull: 'Số CMND/CCCD không được để trống',
        cardRegex: 'Số CMND/CCCD phải là số',
        cardCheck: 'Số CMND/CCCD không hợp lệ',
        pwdNull: 'Mật khẩu không được để trống',
        pwdCheck: 'Mật khẩu không được ít hơn 8 ký tự',
        conFirmPwd: 'Xác nhận mật khẩu không trùng khớp với mật khẩu',
        emptyAmount: 'Bạn chưa nhập số tiền',
        minAmount: 'Số tiền nạp/rút tối thiểu là 100.000 vnđ',
        phoneIsEmpty: 'Số điện thoại không được để trống',
        phoneRegex: 'Số điện thoại không đúng định dạng',
        phoneCount: 'Số điện thoại chỉ được 10 số',
        taxIdEmpty: 'Mã số thuế không được để trống',
        taxIdSyntax: 'Mã số thuế không được ít hơn 10 ký tự',
        specialCharacters: 'Không được chứa kí tự đặc biệt',
        birthdayEmpty: 'Ngày sinh ',
        birthdayNotNumber: 'Ngày sinh không đúng định dạng ví dụ: 1970-01-01',
        birthdayAge18: 'Chưa đủ 18 tuổi',
        birthdayAge95: 'Vượt quá 95 tuổi',
        errProvince: 'Thành phố không được bỏ trống',
        errDistrict: 'Quận huyện không được bỏ trống',
        errWard: 'Xã phường không được bỏ trống',
        errFunds: 'Nguồn tiền không được bỏ trống',
        errMoveto: 'Chuyển tới không được bỏ trống',
        errKeyBook: 'Mã sổ không được bỏ trống',
        errMsgOldPwdCompare: 'Mật khẩu cũ bạn nhập không đúng',
        errMsgCurrentPwdCompare: 'Mật khẩu nhập lại không trùng khớp',
        errMsgEmpty: 'Mật khẩu nhập không được để trống',
        errMsgLength: 'Mật khẩu nhập phải từ 8 kí tự trở lên',
        errMsgSpecialChar: 'Mật khẩu nhập không được chứa kí tự đặc biệt',
        errMsgSpaceChar: 'Mật khẩu nhập không được chứa kí tự trống',
        errMsgUpperChar: 'Mật khẩu phải có 1 kí tự in hoa',
        errMsgGender: 'Giới tính không được bỏ trống',
        genderRequired: 'Giới tính không được để trống',
        emptyList: 'Không có dữ liệu',
        emptyOTP: 'Mã OTP không được để trống',
        userOTPLength: 'Mã OTP không đủ 6 kí tự',
        errMsgOTP: 'Mã OTP không hợp lệ',
        uploadingError: 'Tải ảnh thất bại!',
        errEmptyIdentity: 'Bạn cần điền đầy đủ thông tin trước khi xác thực!',
        errEmptyPhoto: 'Bạn cần tải lên đầy đủ ảnh mặt trước, mặt sau CMT/CCCD và ảnh chân dung trước khi xác thực!',
        errStkEmpty: 'Số tài khoản hoặc số thẻ trống',
        errNameEmpty: 'Tên chủ tài khoản ngân hàng trống',
        errBankEmpty: 'Ngân hàng chưa được chọn',
        errStk: 'Số tài khoản hoặc số thẻ ít hơn giới hạn cho phép',
        errDescribeRatingEmpty: 'Bạn cần viết đánh giá trước khi gửi lên!'
    },
    tabs: ['Đầu tư TienNgay', 'Đầu tư', 'Quản lý', 'Truyền thông', 'Tài khoản'],
    header: {
        textCenter: 'HƯỚNG DẪN SỬ DỤNG CHỨC NĂNG CƠ CẤU, GIA HẠN',
        textCenter1: 'HƯỚNG DẪN SỬ DỤNG BẢO HIỂM',
        name: '',
        personalInformation: 'Thông tin cá nhân',
        setting: 'Cài đặt tài khoản',
        logout: 'Đăng xuất'
    },
    footer: {
        tienNgay: 'TienNgay',
        copyRight: '© 2021-2023 - Bản quyền thuộc Công ty Cổ phần Tài chính Việt',
        companyName: ' CÔNG TY CỔ PHẦN CÔNG NGHỆ TÀI CHÍNH VIỆT',
        companyAddress: ' Tầng 15, Khối B, Tòa nhà Sông Đà, Phạm Hùng, Mỹ Đình 1, Nam Từ Liêm, Hà Nội',
        email: 'Email: contact@tienngay.vn',
        emailHref: 'mailto:contact@tienngay.vn',
        phone: 'Phone: 1900 6907',
        phoneHref: 'tel:19006907',
        information: 'Thông tin',
        informationChild: ['Truyền thông', 'Tuyển dụng', 'Điều kiện và điều khoản'],
        customerSupport: 'Hỗ trợ khách hàng',
        customerChild: ['Sản phẩm', 'Điểm giao dịch'],
        customerFeedback: 'Mọi góp ý của bạn là niềm hạnh phúc của chúng tôi',
        yourComments: 'Góp ý của bạn',
        sendFeedback: 'Gửi phản hồi',
        yourName: 'Tên của bạn',
        phoneNumber: 'Số điện thoại',
        emailFeedback: 'Email',
        successPost: 'Góp ý của bạn là niềm hạnh phúc của chúng tôi!'
    },
    auth: {
        login: 'Đăng nhập',
        register: 'Đăng ký',
        intro: ['CHÀO MỪNG ĐẾN VỚI ĐẦU TƯ TIỆN NGAY', 'Xây dựng tương lai', 'Tiếp cận nhanh chóng các khoản đầu tư có chất lượng cao', 'Tải miễn phí trên AppStore/ Google Play'],
        congrats: ['CHÚC MỪNG BẠN ĐÃ ĐĂNG KÝ THÀNH CÔNG TÀI KHOẢN ĐẦU TƯ TIỆN NGAY', 'Vui lòng tải miễn phí trên AppStore/ Google Play để tiếp tục sử dụng dịch vụ'],
        notAccountYet: 'Bạn chưa có tài khoản?',
        accountYet: 'Bạn đã có tài khoản?',
        registerNow: 'Đăng ký ngay',
        loginNow: 'Đăng nhập ngay',
        savePwd: 'Lưu mật khẩu',
        forgotPwd: 'Quên mật khẩu',
        phone: 'Số điện thoại',
        pwd: 'Mật khẩu',
        or: 'Hoặc',
        facebook: 'facebook',
        google: 'Google',
        signUp: 'Đăng ký',
        name: 'Họ và tên',
        email: 'Email',
        channel: 'Bạn biết chúng tôi qua kênh nào',
        presenter: 'Mã giới thiệu',
        pwdConfirm: 'Xác nhận mật khẩu',
        sendConfirm: 'Gửi xác nhận',
        getBackPass: 'Lấy lại mật khẩu',
        enterAuthCode: 'Nhập mã xác thực',
        confirm: 'Xác nhận',
        contentForgotPwdEnd: '. Hãy kiểm tra và nhập mã xác nhận để lấy lại mật khẩu.',
        contentSignEnd: '. Hãy kiểm tra và nhập mã xác nhận để đăng ký tài khoản.',
        codeConfirm: 'Mã xác nhận',
        changePwd: 'Đổi mật khẩu',
        sendToAfterOTP: 'Gửi lại mã sau',
        sendToOTP: 'Gửi lại mã',
        minute: 'phút',
        loginAccountNow: 'Đăng nhập vào tài khoản bạn ngay',
        registerAccountNow: 'Tạo tài khoản ngay bây giờ',
        forgotNow: 'Điền số điện thoại của bạn và chúng tôi sẽ giúp bạn lấy lại tài khoản của bạn. ',
        contentLinkSocial: 'Xin vui lòng nhập các thông tin dưới đây để hoàn thành việc đăng ký tài khoản.',
        socialGoogle: 'Đăng ký liên kết tài khoản với Google',
        sendOTP: 'Gửi mã',
        txtRefCode: 'Mã giới thiệu',
        contentOTPStart: 'Chúng tôi đã gửi cho bạn một mã xác nhận 6 số qua số điện thoại ',
        contentOTPEnd: '. Hãy kiểm tra và nhập mã xác nhận để đăng ký liên kết tài khoản google thành công.',
        questionIsEmployee: 'Bạn có phải là CBNV của tập đoàn NextTech không?'
    },
    home: {
        logout: 'Bạn có chắc chắn muốn đăng xuất?'
    },
    invest: {
        investAmountChoose: 'Chọn số tiền đầu tư',
        dateInvestChoose: 'Chọn thời gian đầu tư',
        investAmount: 'Số tiền đầu tư',
        dateInvest: 'Thời gian đầu tư',
        yourChance: 'Có $count cơ hội cho bạn',
        yourChanceSearch: 'Tìm kiếm cơ hội đầu tư',
        interestYear: 'Lãi suất năm',
        expectedProfit: 'Lãi dự kiến',
        interestPayForm: 'Hình thức trả lãi: ',
        investNow: 'Đầu tư ngay',
        investPackage: 'Gói đầu tư nổi bật',
        superInvestPackage: 'Gói đầu tư siêu lợi nhuận',
        investTienNgay: 'ĐẦU TƯ TIỆN NGAY',
        buildFuture: 'Xây dựng tương lai',
        describe: 'Tiếp cận nhanh chóng các khoản đầu tư có chất lượng cao',
        contractId: 'Mã số hợp đồng',
        investmentTerm: 'Kỳ hạn đầu tư',
        expectedDueDate: 'Ngày đáo hạn dự kiến',
        expectedDate: 'Ngày đáo hạn',
        totalProfitReceived: 'Tổng lãi nhận được',
        monthlyInterestRate: 'Lãi suất hàng tháng',
        monthlyInterest: 'Lãi trung bình hàng tháng',
        formInterest: 'Hình thức trả lãi',
        investNote: 'Lưu ý khi đầu tư',
        infoContract: 'Thông tin hợp đồng',
        noteAuth: 'Đăng nhập hoặc đăng ký ngay',
        noteVerify: 'Bạn chưa xác thực tài khoản',
        describeAuth: 'Đăng nhập hoặc đăng ký để tiến hành đầu tư ngay hôm nay ',
        describeVerify: 'Xác thực tài khoản để tăng độ an toàn khi đầu tư và sử dụng ứng dụng',
        datePayment: 'Ngày thanh toán',
        principalAmount: 'Số tiền gốc',
        interestAmount: 'Số tiền lãi',
        totalAmount: 'Tổng tiền',
        amountDemandedForInvestment: 'Số tiền cần đầu tư',
        verifyInvest: 'Xác nhận đầu tư',
        investMethod: 'Phương thức đầu tư',
        nganLuongAcc: 'Tài khoản Ngân Lượng',
        bankAcc: 'Tài khoản ngân hàng',
        next: 'Để sau',
        verifyNow: 'Xác thực ngay',
        searchInvestPackage: 'Tìm kiếm gói đầu tư',
        cancel: 'Huỷ bỏ',
        seeMore: 'Xem thêm các gói đầu tư khác',
        estimatedPaymentSchedule: 'Lịch thanh toán dự kiến',
        agreePolicy: 'Tôi đã đọc và đồng ý với $ của TienNgay.vn',
        policy: 'Điều khoản sử dụng và chính sách',
        discoveryNow: 'Khám phá ngay',
        moreInvest: 'Xem thêm các gói đầu tư khác',
        topUpSuccess: 'TienNgay đã nhận được khoản tiền của bạn.',
        unconfirmed: 'Bạn chưa xác thực tài khoản!',
        contentUnconfirmed: 'Xác thực tài khoản để tăng độ an toàn khi đầu tư và sử dụng ứng dụng',
        noAccount: 'Bạn chưa có tài khoản nhận lãi!',
        contentNoAccount: 'Bạn chưa cập nhật hình thức nhận tiền lãi đầu tư. Cập nhật và trải nghiệm đầu tư ngay',
        contentWaitingConfirm: 'Chứng từ của bạn đang được xác minh, bạn có thể tiến hành đầu tư sau khi chứng từ đã được xác thực',
        waitingConfirm: 'Chờ xác minh chứng từ !',
        agreePolicyToInvest: 'Bạn cần phải tích ô đồng ý với điều khoản sử dụng và chính sách của TienNgay để tiến hành đầu tư!',
        choosePaymentMethod: 'Bạn chưa chọn phương thức đầu tư. Cập nhật và trải nghiệm đầu tư ngay!',
        bankAccountEmpty: 'Bạn chưa cập nhật hình thức nhận tiền lãi đầu tư bằng tài khoản ngân hàng. Cập nhật và trải nghiệm đầu tư ngay!',
        typeInterest: 'Hình thức trả lãi',
        chooseTypeInterest: 'Chọn hình thức trả lãi',
        noDataInvest: 'Bạn chưa có khoản đầu tư nào',
        noDataInvestFilter: 'Không có gói đầu tư nào',
        listInvest: 'Danh sách gói đầu tư',
        products: 'Sản phẩm',
        paymentNganLuong: 'Thanh toán qua Ngân lượng',
        investMore: 'Đầu tư thêm',
        seeDetail: 'Xem chi tiết',
        seeListInvesting: 'Xem danh sách gói đang đầu tư',
        investSuccess: 'Đầu tư thành công',
        descriptionLoadingNganLuong: [
            'Hoá đơn Ngân Lượng đã được mở trong thẻ mới!',
            'Đã chuyển tiền - Khách hàng khi chuyển tiền thành công hãy nhấn nút vào đây để sử dụng thêm các tác vụ khác',
            'Lưu ý: Khi chuyển tiền thành công, khách hàng sẽ không thể hủy hoá đơn vừa tạo'
        ],
        transferSuccess: 'Đã chuyển tiền',
        noteInvestSuccess: 'Giao dịch của quý khách sẽ được xử lí sau vài phút kể từ khi chuyển khoản',
        loadingTransaction: 'Giao dịch đang được xử lí',
        notTransfer: 'Chuyển khoản sau',
        updateBankInfo: 'Cập nhật tài khoản ngân hàng'
    },
    intro: {
        invest: 'ĐẦU TƯ TIỆN NGAY',
        buildTheFuture: 'Xây dựng tương lai',
        contentResult: 'Tiếp cận nhanh chóng các khoản đầu tư có chất lượng cao',
        contentStart: 'Đầu tư Tiện Ngay ',
        contentEnd: 'là sản phẩm đầu tư tài chính an toàn và hiệu quả dành cho người Việt, được phát triển bởi TienNgay.vn (Công ty cổ phần Tài Chính Việt) - Một công ty thuộc hệ sinh thái tập đoàn NextTech. Với các sản phẩm đầu tư tài chính 4.0 cá nhân đa dạng cùng sự minh bạch về tài chính và nền tảng công nghệ mạnh, Đầu tư Tiện Ngay giúp bạn đầu tư và tích lũy từ nguồn vốn nhỏ để tạo ra giá trị và bảo vệ tương lai.',
        advantagesTienngay: 'Ưu điểm khi đầu tư tại Tiện Ngay',
        advantagesDownLineTienngay: 'Ưu điểm khi đầu tư tại /n Tiện Ngay',
        riskReduction: 'Giảm thiểu rủi ro',
        riskReductionContent: 'Minh bạch về số tiền đầu tư và lãi suất thu được. Thông tin giao dịch được bảo mật tuyệt đối.',
        ecosystemNextTech: 'Sản phẩm thuộc hệ sinh thái tập đoàn NextTech.',
        ecosystemNextTechContent: 'Tài sản của bạn được quản lý và bảo vệ bởi công ty thuộc tập đoàn công nghệ hàng đầu NextTech',
        appInvest: 'App đầu tư tài chính 4.0 dành cho người Việt',
        appInvestContent: 'Tiện ích vượt trội giúp Nhà Đầu Tư dễ dàng quản lý dòng tiền và các giao dịch tài chính.',
        flexibleTime: 'Linh hoạt thời hạn',
        flexibleTimeContent: 'Vòng đầu tư với lãi suất linh hoạt từ 3 tháng - 24 tháng.',
        seeInvest: 'Xem các khoản đầu tư',
        stepsInvest: 'Đầu tư với 3 bước đơn giản',
        step1: 'Tải xuống và tạo tài khoản chỉ trong vài giây',
        step2: 'Chọn gói đầu tư phù hợp',
        step3: 'Theo dõi lợi nhuận trả về hàng tháng',
        stepContent: 'Chỉ với ba bước đơn giản bạn đã có thể tối ưu dòng tiền của mình.',
        registerApp: 'Tải miễn phí trên AppStore/ Google Play',
        registerPhone: 'Đăng ký bằng SĐT',
        register1Minute: 'Đăng ký nhanh chóng chỉ với 1 phút',
        investmentReasons: 'Shark "tri kỷ" Nguyễn Hòa Bình chia sẻ 3 lý do nên lựa chọn đầu tư với TienNgay.vn',
        transparency: 'Minh bạch',
        transparencyContent: 'Giấy tờ kinh doanh, pháp lý theo đúng quy định của Nhà nước.',
        lasting: 'Bền vững',
        lastingContent: 'Linh hoạt, sinh lời dài hạn và an toàn.',
        easy: 'Dễ dàng',
        easyContent: 'Người không chuyên cũng có thể tham gia đầu tư với khởi điểm từ 3 triệu đồng.',
        investAttractive: 'Các gói đầu tư hấp dẫn tại Tiện Ngay',
        investors: 'Nhà đầu tư',
        investmentMoney: 'Tiền đầu tư',
        profit: 'Lợi nhuận',
        contentInvest1: 'Gói đầu tư đa dạng với từng khách hàng',
        contentInvest2: 'Lãi xuất lên đến 18%',
        contentInvest3: 'Đầu tư linh động chỉ từ 3 tháng',
        contentProfit1: 'Chi tiết các khoản đầu tư minh bạch',
        contentProfit2: 'Lịch sử trả lãi rõ ràng',
        contentProfit3: 'Lãi luôn về đúng hạn',
        serviceHot: 'Dịch vụ siêu tiện ích',
        downloadApp: 'Tải App ngay hôm nay',
        appMobile: ['Tải ứng dụng', ' Đầu tư Tiện Ngay ', 'miễn phí tại Google Play và App Store để hưởng nhiều ưu đãi và những khoản đầu tư hấp dẫn ngay hôm nay!'],
        noInvestHot: 'Chưa có gói đầu tư nào'
    },

    profile: {
        notification: 'Chưa xác thực tài khoản',
        edit: 'Chỉnh sửa',
        infoAccount: 'Thông tin cá nhân',
        titleDrawerAccount: 'Tài khoản cá nhân',
        infoIdentity: 'Xác thực tài khoản',
        userName: 'Họ và tên',
        birthday: 'Ngày sinh',
        gender: 'Giới tính',
        phone: 'Số điện thoại',
        email: 'Email',
        address: 'Địa chỉ',
        unConfirmed: 'Thông tin cá nhân của bạn chưa được xác thực, vui lòng xác thực tài khoản trước khi tiến hành đầu tư.',
        waitConfirmed: 'Thông tin cá nhân của bạn đang chờ xác thực, vui lòng chờ xác thực tài khoản trước khi tiến hành đầu tư.',
        confirmed: 'Thông tin cá nhân của bạn đã được xác thực, tài khoản của bạn đã có thể tiến hành đầu tư.',
        editAccount: 'Chỉnh sửa thông tin cá nhân',
        infoPayment: 'Thông tin thanh toán',
        accountNumber: 'Số tài khoản',
        accountName: 'Tên tài khoản',
        bank: 'Ngân hàng',
        noteBank: 'Chú ý: ',
        contentNoteBank: 'Đây là tài khoản ngân hàng để nhận lãi, bạn cần đảm bảo chính xác thông tin tài khoản ngân hàng bạn cung cấp là chính xác.',
        contentTienNgayFirst: ' TienNgay.vn ',
        contentTienngayEnd: 'sẽ không chịu trách nghiệm khi bạn nhập sai thông tin. ',
        passCurrent: 'Mật khẩu cũ',
        passNew: 'Mật khẩu mới',
        passConfirmNew: 'Nhập lại mật khẩu mới',
        investmentIntroduction: 'Giới thiệu nhà đầu tư',
        codeIntroduction: 'Mã giới thiệu của bạn',
        linkIntroduction: 'Liên kết tải ứng dụng',
        qrApp: 'QR code tải ứng dụng',
        copySuccess: 'Sao chép bản ghi thành công',
        accountLink: 'Các tài khoản liên kết',
        ggLink: 'Liên kết Goggle',
        linked: 'Đã liên kết',
        unlinked: 'Chưa liên kết',
        logout: 'Đăng xuất',
        empty: 'Trống',
        successEditAvatar: 'Cập nhật ảnh đại diện thành công!',
        changePass: 'Đổi mật khẩu',
        successChangePassNotify: 'Xác nhận đổi mật khẩu thành công!',
        userManual: 'Hướng dẫn sử dụng',
        numberATM: 'Số thẻ ATM'
    },
    news: {
        investTienngay: 'Đầu tư Tiện ngay vàng về liền tay',
        view: 'Lượt xem',
        loremIpsum: 'What is Lorem Ipsum?',
        loremIpsumContent: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry is standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        new: 'Tin mới',
        other: 'Tin khác'
    },
    transferBank: {
        describeTransfer: 'Để nạp tiền, bạn hãy dùng bất kỳ ngân hàng nào để chuyển khoản đến tài khoản sau:',
        receiverBankName: 'Ngân hàng nhận',
        receiverBankOwner: 'Tên tài khoản nhận',
        receiverBankNumber: 'Số tài khoản nhận',
        transferAmount: 'Số tiền cần chuyển',
        transferContent: 'Nội dung chuyển khoản',
        noteTransfer: 'Nếu nội dung chuyển khoản thiếu hoặc không chính xác. Chúng tôi sẽ không thể nhận ra giao dịch của bạn.',
        qrAction: 'Hoặc thực hiện scan mã Qr code sau:',
        copy: 'Sao chép',
        bank: 'Ngân hàng',
        bankNumber: 'Số Tài khoản',
        copySuccess: 'Sao chép hoàn tất!'
    },
    report: {
        title: 'Báo cáo',
        financialChart: 'Biểu đồ chi phí đầu tư và thu về',
        month: 'Tháng',
        overviewInvest: 'Tổng quan đầu tư',
        year: 'Năm',
        million: 'Triệu',
        reportColumnValue: ['Tiền đầu tư', 'Tổng gốc đã nhận', 'Tổng lãi đã nhận'],
        reportQuarter: 'Báo cáo năm ',
        totalInterest: 'Tổng lãi',
        totalProfitReceived: 'Tổng lãi đã nhận',
        totalInvestment: 'Tổng vốn đầu tư',
        totalCapitalReceived: 'Tổng vốn đã nhận',
        totalRemainingCapital: 'Tổng vốn còn lại',
        totalProfitRemaining: 'Tổng lãi còn lại'
    },
    manageTabs: ['Lịch sử đầu tư', 'Báo cáo', 'Giao dịch'],
    transactionTabs: ['Tất cả', 'Tiền ra', 'Tiền vào'],
    transaction: {
        infoTransactions: 'Thông tin giao dịch',
        search: 'Tìm kiếm',
        describeNoData: 'Không có giao dịch hiển thị',
        table: {
            stt: 'STT',
            money: 'Tổng',
            content: 'Nội dung',
            contractId: 'Mã hợp đồng',
            time: 'Thời gian'
        },
        seeMoreTransaction: 'Xem thêm các giao dịch khác'
    },
    historyTabs: ['Đang đầu tư', 'Đã đáo hạn'],
    history: {
        searchInvestPackage: 'Tìm kiếm gói đầu tư',
        interestReceived: 'Lãi đã nhận',
        remainingOriginal: 'Gốc còn lại',
        havePackage: 'Bạn có $count gói đầu tư',
        haveInvested: 'Bạn từng đầu tư $count gói',
        fromDate: 'Từ ngày',
        toDate: 'Đến ngày',
        searchProjectInvest: 'Tìm kiếm dự án đầu tư',
        dateInvest: 'Ngày đầu tư',
        expectedDueDate: 'Ngày đáo hạn dự kiến',
        expectedDate: 'Ngày đáo hạn'
    },
    historyDetail: {
        remainingOriginalAmount: 'Số tiền gốc còn lại',
        receivedOriginalAmount: 'Số tiền gốc đã nhận',
        dateInvest: 'Ngày đầu tư',
        receivedInterest: 'Lãi đã nhận',
        remainingInterest: 'Lãi còn lại',
        payInterestInfo: 'Thông tin trả lãi',
        payed: 'Đã thanh toán',
        unPayed: 'Chưa tới hạn'
    },
    identity: {
        title: 'Xác thực tài khoản',
        describeIdentity: 'Cập nhập thông tin chứng từ để xác thực tài khoản',
        identity: 'Số CMND/CCCD',
        inputIdentity: 'Nhập số CMND/CCCD',
        photoKyc: 'Ảnh giấy tờ tùy thân',
        photoPortrait: 'Ảnh chân dung chụp:',
        frontKyc: 'Mặt trước chứng từ',
        behindKyc: 'Mặt sau chứng từ',
        portrait: 'Chân dung khuôn mặt',
        reChoose: 'Chọn lại',
        verify: 'Xác nhận chứng từ',
        showFull: 'Xem đầy đủ'
    },
    commission: {
        investmentCommission: 'Hoa hoa hồng nhà đầu tư',
        star: '* ',
        describeNoData: 'Không có dữ liệu hiển thị',
        describe: [
            'Số tiền hoa hồng được hiển thị trong tháng hiện tại là tạm tính và có thể thay đổi theo tổng số tiền đầu tư hàng tháng',
            'Chính sách chỉ áp dụng khi người được bạn giới thiệu có đầu tư vào TienNgay. Chính sách có hiệu lực từ ngày %str'
        ],
        total: 'Tổng',
        totalInvestAmount: 'Tổng tiền đầu tư',
        investAmount: 'Tiền đầu tư',
        totalCommission: 'Tổng hoa hồng',
        commissionAmount: 'Hoa hồng',
        chooseDate: 'Chọn ngày'
    },
    msgNotify: {
        successAccountLinkBank: 'Liên kết thành công tài khoản ngân hàng'
    },
    policy: {
        titlePolicy: 'ĐIỀU KHOẢN SỬ DỤNG HỆ THỐNG ỨNG DỤNG TIENNGAY.VN APP',
        describePolicy: 'Nội dung Bản điều khoản sử dụng dịch vụ TienNgay.vn app dưới đây tạo thành một Hợp đồng sử dụng dịch vụ ràng buộc về mặt pháp lý giữa Công Ty Cổ Phần Công Nghệ Tài Chính Việt và Khách hàng. Khi sử dụng dịch vụ TienNgay.vn app có nghĩa là khách hàng đã chấp nhận các Điều khoản và điều kiện dưới đây, đồng thời chịu sự ràng buộc phải tuân thủ bởi các điều khoản và điều kiện đó. Khách hàng có trách nhiệm xem xét và đọc kỹ nội dung của Bản điều khoản này, nếu khách hàng không đồng ý với các điều kiện và điều khoản này thì nên chấm dứt sử dụng ứng dụng này.',
        bigHeader: [
            '1. Mô tả dịch vụ',
            '2. Quyền và trách nhiệm của Khách hàng',
            '3. Quyền và trách nhiệm của VFC',
            '4. Rủi ro và miễn trừ trách nhiệm',
            '5. Luật áp dụng và giải quyết tranh chấp',
            '6. Điều khoản cuối cùng'
        ],
        subTitlePolicy: {
            article1: [
                'Ứng dụng TienNgay.vn app là phần mềm công nghệ cung cấp dịch vụ tư vấn quản lý do Công Ty Cổ Phần Công Nghệ Tài Chính Việt (sau đây gọi là “VFC”) phát hành, theo đó, Người sử dụng dịch vụ có thể quản lý khoản đầu tư của mình một cách chi tiết khi sử dụng ứng dụng thông qua thiết bị di dộng.'
            ],
            article2: [
                '2.1. Đọc, hiểu, tuân thủ các thủ tục đăng ký, trình tự giao dịch và các quy định, hướng dẫn sử dụng và Bản điều khoản điều kiện này trước khi sử dụng dịch vụ của chúng tôi.',
                '2.2. Sử dụng đúng mục đích những thông tin dịch vụ do Ứng dụng cung cấp.',
                '2.3. Cung cấp đầy đủ, chính xác các thông tin cần thiết khi đăng ký và/hoặc phát sinh trong quá trình sử dụng dịch vụ theo yêu cầu của VFC.',
                '2.4. Tuân thủ các quy định pháp luật và quy định của VFC liên quan đến việc đăng ký và sử dụng Dịch vụ ứng dụng.',
                '2.5. Không sử dụng Ứng dụng hoặc Phần mềm để gây khó khăn hoặc rối loạn hoạt động hoặc làm giả yêu cầu sử dụng dịch vụ.',
                '2.6. Không sao chép, hoặc phân phối Phần mềm hoặc nội dung khác mà không có sự cho phép bằng văn bản của VFC.',
                '2.7. Giữ an toàn và bảo mật mật khẩu tài khoản của mình hoặc bất kỳ phương thức nhận dạng nào mà VFC cung cấp để bạn truy cập vào Dịch vụ.',
                '2.8. VFC có quyền nhưng không bắt buộc phải chấm dứt Hợp đồng này và chấm dứt việc sử dụng Dịch vụ của bạn bất kỳ lúc nào mà có hoặc không thông báo; có quyền ngừng xử lý bất kỳ một giao dịch nào mà VFC cho rằng giao dịch đó có thể là lừa đảo, bất hợp pháp hoặc có liên quan tới các hành vi phạm tội hoặc khi VFC cho rằng Khách hàng đang vi phạm Điều khoản sử dụng.',
                '2.9. Cập nhật, theo dõi các thông tin, thông báo, quy định, hướng dẫn về sử dụng Dịch vụ của VFC theo các phương thức như: (i) cập nhật trên Ứng dụng; (ii) tài liệu hướng dẫn của VFC; (iii) thông báo, hướng dẫn qua email, tin nhắn sms; (iv) các phương thức khác theo quy định của VFC trong từng thời kỳ.',
                '2.10. Gửi yêu cầu hỗ trợ, khiếu nại trong quá trình sử dụng Dịch vụ cho VFC thông qua các hình thức: gọi điện thoại đến Tổng đài hỗ trợ dịch vụ Khách hàng hoặc hình thức khác theo quy đinh của VFC.',
                '2.11. Hợp tác và cung cấp thông tin cần thiết theo yêu cầu của chúng tôi phù hợp với thỏa thuận với VFC và quy định pháp luật.',
                '2.12. Các nghĩa vụ khác theo quy định của VFC và các quy định có liên quan của pháp luật.'
            ],
            article3: [
                '3.1. VFC có quyền sở hữu tất cả các quyền, quyền sở hữu và lợi ích, bao gồm tất cả các quyền sở hữu tài sản trí tuệ có liên quan, đối với Phần mềm và/hoặc Ứng dụng. Khách hàng không được phép sao chép, điều chỉnh hoặc sử dụng lại Nội dung tại TienNgay.vn app mà không có sự cho phép trước bằng văn bản của VFC.',
                '3.2. Tuân thủ các quy định của pháp luật liên quan đến việc cung ứng dịch vụ.',
                '3.3. Đảm bảo cung cấp chính xác, đầy đủ các dịch vụ cho Khách hàng theo thỏa thuận',
                '3.4. Cung cấp tài liệu hướng dẫn, hỗ trợ Khách hàng sử dụng dịch vụ.',
                '3.5. Giải đáp thắc mắc, khiếu nại của Khách hàng liên quan đến dịch vụ.',
                '3.6. Bảo mật các thông tin của Khách hàng được lưu tại VFC, trừ trường hợp phải thực hiện cung cấp thông tin theo quy định của pháp luật.',
                {
                    title: '3.7. Khóa/tạm ngừng/chấm dứt/ hoặc từ chối việc thực hiện giao dịch hoặc tạm ngưng dịch vụ hoặc khóa chức năng đăng nhập của Khách hàng trong quá trình sử dụng Dịch vụ mà không cần phải báo trước cho Khách hàng khi xảy ra các trường hợp như sau:',
                    subTitle: [
                        'Tạm ngưng dịch vụ để nâng cấp, bảo trì hệ thống;',
                        'Khi phát hiện Khách hàng vi phạm bất kỳ nội dung nào trong Bản điều khoản điều kiện này, các quy định về việc sử dụng Ứng dụng do VFC ban hành hoặc các quy định pháp luật có liên quan;',
                        'Giao dịch của Khách hàng có dấu hiệu vi phạm pháp luật;',
                        'Theo quyết định và/hoặc yêu cầu của cơ quan nhà nước có thẩm quyền.'
                    ]
                },
                '3.8. Không chịu trách nhiệm về bất kỳ tranh chấp phát sinh nào giữa Khách hàng và bên thứ ba (nếu có) phát sinh từ hoặc liên quan đến các giao dịch được thực hiện không thông qua dịch vụ của Ứng dụng.',
                '3.9. Thay đổi tài liệu liên quan đến dịch vụ, thay đổi/điều chỉnh thông tin giao diện màn hình, chức năng dịch vụ vào bất kỳ thời điểm nào mà không cần phải báo trước cho Khách hàng.',
                '3.10. Khi nâng cấp, phát triển dịch vụ, VFC được phép bổ sung, cung cấp thêm các tiện ích dịch vụ cho Khách hàng mà không cần thông báo hoặc yêu cầu Khách hàng đăng ký bổ sung dịch vụ.',
                '3.11. Khi Khách hàng truy nhập và sử dụng ứng dụng , VFC có thể thu thập và lưu trữ các thông tin như các số liệu thống kê quá trình truy cập, các thông tin cá nhân cung cấp cho VFC khi đăng ký… Các thông tin cá nhân Khách hàng cung cấp bao gồm nhưng không giới hạn bởi tên, ngày sinh, số điện thoại, địa chỉ email, địa chỉ thường trú, địa chỉ sử dụng dịch vụ.... VFC có quyền sử dụng các thông tin này vào việc lập kế hoạch, nghiên cứu, quản lý, giám sát, tư vấn, hỗ trợ giữa VFC với Khách hàng và (hoặc) sử dụng vào mục đích quảng bá, giới thiệu sản phẩm dịch vụ của VFC cho Khách hàng hoặc cung cấp thông tin cho các cơ quan pháp luật theo yêu cầu của Luật pháp hoặc của Toà án.',
                '3.12. Các quyền khác theo quy định của VFC và của pháp luật.'
            ],
            article4: {
                title: 'Chúng tôi cam kết cung cấp Dịch vụ tốt nhất và cố gắng giảm thiểu các rủi ro có thể gặp phải về kỹ thuật cho Khách hàng; không chịu trách nhiệm về những rủi ro, thiệt hại của Khách hàng khi Khách hàng sử dụng Dịch vụ do những rủi ro sau:',
                subTitle: [
                    'Lỗi hệ thống phần cứng, phần mềm không hoạt động hoặc hoạt động không đúng chức năng thiết kế do các yếu tố bất khả kháng gây ra như lũ lụt, hỏa hoạn, thiên tai, chập điện, hư hỏng tự nhiên …;',
                    'Nguy cơ ngưng trệ hoạt động của hệ thống mạng do lỗi đường truyền Internet, mạng điện thoại di động … của nhà cung cấp dịch vụ gặp sự cố kỹ thuật hoặc quá tải;',
                    'Hệ thống có thể bị nhiễm virus, bị tấn công hoặc bị ảnh hưởng của những sự cố ngoài tầm kiểm soát của VFC làm ngưng trệ các hoạt động trao đổi thông tin; dẫn đến việc không thể xử lý hoặc thực hiện các giao dịch của Khách hàng;',
                    'Việc nhận dạng có thể bị nhầm, sai sót do các thông tin nhận dạng Khách hàng (tên truy cập, mật khẩu truy cập, số điện thoại, địa chỉ thư điện tử) bị bên thứ 3 chiếm đoạt bằng các thủ đoạn bất hợp pháp…;',
                    'Rủi ro lệnh giao dịch một khi đã được Khách hàng gửi đi thì không thể thu hồi do các giao dịch trên hệ thống Ứng dụng của chúng tôi được xử lý và thực hiện một cách tự động.',
                    'Khách hàng sẽ chịu trách nhiệm hoàn toàn về các quyết định liên quan đến các dịch vụ và sản phẩm được giới thiệu tới khách hàng thông qua dịch vụ, phần mềm và/hoặc ứng dụng. Khách hàng hoàn toàn bãi bỏ và miễn trừ VFC khỏi bất kỳ và mọi trách nhiệm pháp lý, khiếu nại, nguyên nhân khởi tố, hay thiệt hại nào xuất phát từ việc sử dụng dịch vụ, phần mềm và/hoặc ứng dụng của khách hàng, hoặc trong bất kỳ cách nào liên quan đến các bên thứ ba đã được giới thiệu tới khách hàng thông qua dịch vụ, phần mềm và/hoặc ứng dụng.'
                ]
            },
            article5: [
                '5.1. Điều kiện, điều khoản Dịch vụ này được điều chỉnh bởi pháp luật Việt Nam.',
                '5.2. Trong quá trình thực hiện nếu phát sinh tranh chấp, hai bên sẽ chủ động giải quyết trên cơ sở thương lượng, hòa giải. Trường hợp không giải quyết được, tranh chấp sẽ được đưa ra Tòa án có thẩm quyền theo quy định pháp luật để giải quyết, trừ trường hợp pháp luật có quy định khác.'
            ],
            article6: [
                '6.1. Các vấn đề chưa được quy định tại Điều kiện, điều khoản này sẽ được thực hiện theo quy định của pháp luật, hướng dẫn của cơ quan Nhà nước có thẩm quyền và/hoặc các cam kết/thỏa thuận có hiệu lực khác giữa các bên.',
                '6.2. Khách hàng đã đọc, hiểu, nhất trí và cam kết thực hiện đúng các quy định tại Điều kiện, điều khoản sữ dụng này.',
                '6.3. Điều kiện, điều khoản này có hiệu lực kể từ ngày Khách hàng thực hiện đăng ký và sử dụng dịch vụ ứng dụng/phần mềm của VFC.'
            ]
        }
    },
    questionAnswer: {
        titlePage: 'Hỏi đáp Nhà Đầu Tư',
        bigHeader: [
            '1. Chứng chỉ quỹ là gì?',
            '2. Có nên đầu tư chứng chỉ quỹ?',
            '3. Quỹ hoán đổi danh mục - quỹ ETF là gì?',
            '4. Sản phẩm Đầu tư có cam kết lợi nhuận không?',
            '5. Tiện Ngay có an toàn không?',
            '6. Tài sản đầu tư của tôi tăng hay giảm do đâu?',
            '7. Thời gian rút tiền đầu tư mất bao lâu?',
            '8. Mức đầu tư tối thiểu là bao nhiêu?',
            '9. Lãi suất bao nhiêu phần trăm?'
        ],
        subTitleQA: {
            article1: [
                'Chứng chỉ quỹ là một loại chứng khoán nhằm xác nhận quyền sở hữu một phần vốn góp trong quỹ đại chúng của Nhà đầu tư. Quỹ đại chúng được hình thành từ vốn góp của nhà đầu tư với mục đích đầu tư kiếm lợi nhuận từ thị trường chứng khoán. Nhà đầu tư khi góp vốn vào quỹ đại chúng thì phải mua chứng chỉ quỹ để xác nhận sự góp vốn của mình và quỹ chung đó.'
            ],
            article2: [
                'Các quỹ ETF có thể là một phương tiện đầu tư tuyệt vời dành cho các nhà đầu tư lớn và nhỏ.'
            ],
            article3: [
                'Quỹ ETF - viết tắt của cụm từ Exchange Traded Fund còn có tên gọi khác là quỹ hoán đổi danh mục. Quỹ ETF là một rổ chứng khoán hoạt động theo chỉ số đại diện cho một tài sản nhất định nào đó như vàng, hàng hóa, chứng khoán, lĩnh vực ngành hàng…'
            ],
            article4: [
                'Tiện Ngay không cam kết bất kì một mức lãi suất cố định nào đối với sản phẩm Đầu Tư.'
            ],
            article5: {
                title: 'Tiện Ngay là ứng dụng đáp ứng các yêu cầu bảo mật cao trong lĩnh vực công nghệ tài chính:',
                subTitle: [
                    'Đảm bảo các tiêu chuẩn bảo mật theo ISO 27001, PCI DSS, Zero Trust.',
                    'Xây dựng ứng dụng theo tiêu chuẩn quốc gia TCVN ISO 31000:2018 về quản lý rủi ro.',
                    'Tiện Ngay có đội ngũ chịu trách nhiệm An toàn thông tin riêng, liên tục cập nhật và cải tiến các tính năng bảo mật, sẵn sàng tiếp nhận và xử lý các vấn đề.'
                ]
            },
            article6: [
                'Tăng giảm tài sản của người dùng đều do tình hình thị trường và hoạt động của các Quỹ đầu tư quyết định. Tài sản của người dùng có thể tăng, giảm hoặc đứng yên tùy vào tình hình thị trường và hoạt động của các Quỹ đầu tư. Ngoài ra, trong một số trường hợp như đầu tư lần đầu hoặc chuyển cấu trúc, các Quỹ đầu tư đang trong quá trình xác nhận cũng có thể khiến tài sản của bạn tạm thời đứng yên, không tăng không giảm.'
            ],
            article7: [
                'Trong vòng tối đa 3 - 5 ngày làm việc, khoản rút của người dùng sẽ về tới tài khoản ngân hàng đã đăng ký.'
            ],
            article8: [
                'Tối thiểu 3.000.000 nhà đầu tư hoàn toàn có thể tận dụng các khoản tiền nhàn rỗi để sinh lời.'
            ],
            article9: [
                'Với tỉ suất lợi nhuận lên tới 15%/năm và kì hạn linh hoạt, các khoản đầu tư thực hiện qua TienNgay.vn Investor sinh lời một cách dễ dàng, thời gian quay vòng vốn nhanh.'
            ]
        }
    },
    notification: {
        titleHeader: 'Thông báo',
        newNotify: ' thông báo mới',
        seeMore: 'Xem thêm thông báo khác',
        noData: 'Bạn chưa có thông báo nào'
    },
    recruit: {
        recruitmentContent: 'TienNgay.vn xây dựng một tập thể lớn đủ mạnh để tiến xa hơn trong lĩnh vực Tài chính. Gia nhập đội ngũ của chúng tôi ngay hôm nay!',
        desire: 'Bạn đang muốn tìm kiếm công việc gì ?',
        textTime: 'Thời gian đầu tư',
        jobPosition: 'Vị trí công việc',
        promotion: 'Đãi ngộ hấp dẫn',
        peers: 'Đồng nghiệp thân thiện',
        opportunity: 'Cơ hội học hỏi, phát triển',
        textPromotion: 'Chúng tôi có chính sách đãi ngộ hấp dẫn, đảm bảo tính cạnh tranh',
        textPeers: 'Chúng tôi tạo nên một môi trường làm việc hoà đồng, thân thiện đầy nhiệt huyết',
        textOpportunity: 'Có cơ hội học hỏi khả năng kinh doanh, trau dồi kiến thức về tài chính',
        discover: 'Khám phá bản thân tại TienNgay.vn'
    }
};


export default Languages;
